development:
  cloud_name: "your cloud name"
  api_key: "cloudinary api key"
  api_secret: "cloudinary api secret"

production:
  cloud_name: "your cloud name"
  api_key: "cloudinary api key"
  api_secret: "cloudinary api secret"